name: Docker image

on:
  push: {}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous jobs for the same PR
        if: "github.event_name == 'pull_request'"
        uses: styfle/cancel-workflow-action@89f242ee29e10c53a841bfe71cc0ce7b2f065abc
        with:
          workflow_id: deb.yml,docker.yml,raspbian.yml,rpm.yml,windows.yml
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker image
        uses: Al2Klimov/docker-icinga2@test3c30865
        env:
          INPUT_TOKEN: '${{ github.token }}'
          DOCKER_HUB_PASSWORD: '${{ secrets.DOCKER_HUB_PERSONAL_TOKEN }}'
